### ISSUE TITLE
Steem Mention needs a logo.

### ISSUE THREAD

**Issue by ety001** [ety001/steem-mention#3]
Steem Mention needs a logo.

**Comment by radudangratian** [comment]
Hello! As we talked on Discord here it's the concept. I hope you will like it and use it. Thank you!


![asset 1-24](https://user-images.githubusercontent.com/34451833/38542205-e7d323ce-3ca9-11e8-8232-6685a6607e02.png)

Below you can find the link with all the files that you need:
https://drive.google.com/open?id=1Z3NWYjRlJPIoyd6Ya9EQN-AJZMMnOOqQ

**Comment by ety001** [comment]
Thanks for your work. Your design has been update to my site. Thanks agian.
